version: '3'

services:
  short_url_war:
    image: privdim/short_url_service
    build: .
    ports:
      - 8080:8080
    links:
      - "db"
    depends_on:
      - db
  db:
    image: privdim/short_url_db
    build: ./db
    ports:
    - 5432:5432
